### ISSUE TITLE
As a student, I want to upload my magazine contribution so that it can be considered for publication.

### ISSUE THREAD

**Issue by hennah-s** [GreenwichEWSD/Documentation#18]
- [x] Add contributions table to DB (id, status, contribution, student)
- [x] Add 'my contributions' page 
  - [x] Add upload functionality
  - [x] Select competition (currently only selects top comp - use !isPostBack
  - [x] View uploads
  - [x] Show status
  - [x] Enable editing of contribution

**Comment by JoeScho** [comment]
Blocked by #21
