### ISSUE TITLE
As a user, I want to see a familiar user interface design, so that I can easily navigate the system

### ISSUE THREAD

**Issue by JoeScho** [GreenwichEWSD/Documentation#2]
Would be great to have a few mockups that show ideas for how the UI will look

**Comment by anisaboom** [comment]
here is an idea of a Bootstrap dashboard I have for the project 
![dashboard example](https://cloud.githubusercontent.com/assets/25183898/22471114/54251b72-e7c9-11e6-8ba3-af56e7499dc8.jpg)
