### ISSUE TITLE
As an administrator, I want to manage the users in the database, so that I can control who has access to the system

### ISSUE THREAD

**Issue by hennah-s** [GreenwichEWSD/Documentation#32]
- [x] Program administrator login @JoeScho
- [x] Database tables created @hennah-s @dj418 @kn307 
- [x] Create homepage @JoeScho
- [x] Design login & homepage @anisaboom 
- [x] Program 'manage users' page on website @JoeScho
  - [ ] Create, Update & Delete users from DB using web interface @JoeScho

**Comment by JoeScho** [comment]
Is this actually required? 
From the spec:
`An administrator maintains any system data, e.g. closure dates for each academic year.`
